/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as ForumsIndexRouteImport } from './routes/forums/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as CreateThreadIndexRouteImport } from './routes/create-thread/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as UserIdIndexRouteImport } from './routes/user/$id/index'
import { Route as TeamIdIndexRouteImport } from './routes/team.$id/index'
import { Route as SearchThreadsIndexRouteImport } from './routes/search/threads.index'
import { Route as MatchIdMatchTitleIndexRouteImport } from './routes/$matchId.$matchTitle/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ThreadIdTitleIndexRouteImport } from './routes/thread.$id.$title/index'
import { Route as NewsIdTitleIndexRouteImport } from './routes/news.$id.$title/index'
import { Route as EventIdTitleIndexRouteImport } from './routes/event.$id.$title/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsIndexRoute = ForumsIndexRouteImport.update({
  id: '/forums/',
  path: '/forums/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateThreadIndexRoute = CreateThreadIndexRouteImport.update({
  id: '/create-thread/',
  path: '/create-thread/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdIndexRoute = UserIdIndexRouteImport.update({
  id: '/user/$id/',
  path: '/user/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIdIndexRoute = TeamIdIndexRouteImport.update({
  id: '/team/$id/',
  path: '/team/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchThreadsIndexRoute = SearchThreadsIndexRouteImport.update({
  id: '/search/threads/',
  path: '/search/threads/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchIdMatchTitleIndexRoute = MatchIdMatchTitleIndexRouteImport.update({
  id: '/$matchId/$matchTitle/',
  path: '/$matchId/$matchTitle/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ThreadIdTitleIndexRoute = ThreadIdTitleIndexRouteImport.update({
  id: '/thread/$id/$title/',
  path: '/thread/$id/$title/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdTitleIndexRoute = NewsIdTitleIndexRouteImport.update({
  id: '/news/$id/$title/',
  path: '/news/$id/$title/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventIdTitleIndexRoute = EventIdTitleIndexRouteImport.update({
  id: '/event/$id/$title/',
  path: '/event/$id/$title/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/': typeof AdminIndexRoute
  '/create-thread/': typeof CreateThreadIndexRoute
  '/events/': typeof EventsIndexRoute
  '/forums/': typeof ForumsIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/test/': typeof TestIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$matchId/$matchTitle/': typeof MatchIdMatchTitleIndexRoute
  '/search/threads/': typeof SearchThreadsIndexRoute
  '/team/$id/': typeof TeamIdIndexRoute
  '/user/$id/': typeof UserIdIndexRoute
  '/event/$id/$title/': typeof EventIdTitleIndexRoute
  '/news/$id/$title/': typeof NewsIdTitleIndexRoute
  '/thread/$id/$title/': typeof ThreadIdTitleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin': typeof AdminIndexRoute
  '/create-thread': typeof CreateThreadIndexRoute
  '/events': typeof EventsIndexRoute
  '/forums': typeof ForumsIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/test': typeof TestIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$matchId/$matchTitle': typeof MatchIdMatchTitleIndexRoute
  '/search/threads': typeof SearchThreadsIndexRoute
  '/team/$id': typeof TeamIdIndexRoute
  '/user/$id': typeof UserIdIndexRoute
  '/event/$id/$title': typeof EventIdTitleIndexRoute
  '/news/$id/$title': typeof NewsIdTitleIndexRoute
  '/thread/$id/$title': typeof ThreadIdTitleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/admin/': typeof AdminIndexRoute
  '/create-thread/': typeof CreateThreadIndexRoute
  '/events/': typeof EventsIndexRoute
  '/forums/': typeof ForumsIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/test/': typeof TestIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$matchId/$matchTitle/': typeof MatchIdMatchTitleIndexRoute
  '/search/threads/': typeof SearchThreadsIndexRoute
  '/team/$id/': typeof TeamIdIndexRoute
  '/user/$id/': typeof UserIdIndexRoute
  '/event/$id/$title/': typeof EventIdTitleIndexRoute
  '/news/$id/$title/': typeof NewsIdTitleIndexRoute
  '/thread/$id/$title/': typeof ThreadIdTitleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/admin/'
    | '/create-thread/'
    | '/events/'
    | '/forums/'
    | '/matches/'
    | '/test/'
    | '/api/auth/$'
    | '/$matchId/$matchTitle/'
    | '/search/threads/'
    | '/team/$id/'
    | '/user/$id/'
    | '/event/$id/$title/'
    | '/news/$id/$title/'
    | '/thread/$id/$title/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/admin'
    | '/create-thread'
    | '/events'
    | '/forums'
    | '/matches'
    | '/test'
    | '/api/auth/$'
    | '/$matchId/$matchTitle'
    | '/search/threads'
    | '/team/$id'
    | '/user/$id'
    | '/event/$id/$title'
    | '/news/$id/$title'
    | '/thread/$id/$title'
  id:
    | '__root__'
    | '/'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/admin/'
    | '/create-thread/'
    | '/events/'
    | '/forums/'
    | '/matches/'
    | '/test/'
    | '/api/auth/$'
    | '/$matchId/$matchTitle/'
    | '/search/threads/'
    | '/team/$id/'
    | '/user/$id/'
    | '/event/$id/$title/'
    | '/news/$id/$title/'
    | '/thread/$id/$title/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CreateThreadIndexRoute: typeof CreateThreadIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  ForumsIndexRoute: typeof ForumsIndexRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  MatchIdMatchTitleIndexRoute: typeof MatchIdMatchTitleIndexRoute
  SearchThreadsIndexRoute: typeof SearchThreadsIndexRoute
  TeamIdIndexRoute: typeof TeamIdIndexRoute
  UserIdIndexRoute: typeof UserIdIndexRoute
  EventIdTitleIndexRoute: typeof EventIdTitleIndexRoute
  NewsIdTitleIndexRoute: typeof NewsIdTitleIndexRoute
  ThreadIdTitleIndexRoute: typeof ThreadIdTitleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches/': {
      id: '/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/': {
      id: '/forums/'
      path: '/forums'
      fullPath: '/forums/'
      preLoaderRoute: typeof ForumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-thread/': {
      id: '/create-thread/'
      path: '/create-thread'
      fullPath: '/create-thread/'
      preLoaderRoute: typeof CreateThreadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/': {
      id: '/user/$id/'
      path: '/user/$id'
      fullPath: '/user/$id/'
      preLoaderRoute: typeof UserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$id/': {
      id: '/team/$id/'
      path: '/team/$id'
      fullPath: '/team/$id/'
      preLoaderRoute: typeof TeamIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/threads/': {
      id: '/search/threads/'
      path: '/search/threads'
      fullPath: '/search/threads/'
      preLoaderRoute: typeof SearchThreadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$matchId/$matchTitle/': {
      id: '/$matchId/$matchTitle/'
      path: '/$matchId/$matchTitle'
      fullPath: '/$matchId/$matchTitle/'
      preLoaderRoute: typeof MatchIdMatchTitleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thread/$id/$title/': {
      id: '/thread/$id/$title/'
      path: '/thread/$id/$title'
      fullPath: '/thread/$id/$title/'
      preLoaderRoute: typeof ThreadIdTitleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id/$title/': {
      id: '/news/$id/$title/'
      path: '/news/$id/$title'
      fullPath: '/news/$id/$title/'
      preLoaderRoute: typeof NewsIdTitleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$id/$title/': {
      id: '/event/$id/$title/'
      path: '/event/$id/$title'
      fullPath: '/event/$id/$title/'
      preLoaderRoute: typeof EventIdTitleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  AdminIndexRoute: AdminIndexRoute,
  CreateThreadIndexRoute: CreateThreadIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  ForumsIndexRoute: ForumsIndexRoute,
  MatchesIndexRoute: MatchesIndexRoute,
  TestIndexRoute: TestIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  MatchIdMatchTitleIndexRoute: MatchIdMatchTitleIndexRoute,
  SearchThreadsIndexRoute: SearchThreadsIndexRoute,
  TeamIdIndexRoute: TeamIdIndexRoute,
  UserIdIndexRoute: UserIdIndexRoute,
  EventIdTitleIndexRoute: EventIdTitleIndexRoute,
  NewsIdTitleIndexRoute: NewsIdTitleIndexRoute,
  ThreadIdTitleIndexRoute: ThreadIdTitleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
