/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as ForumsIndexRouteImport } from './routes/forums/index'
import { Route as CreateThreadIndexRouteImport } from './routes/create-thread/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as UserIdIndexRouteImport } from './routes/user/$id/index'
import { Route as SearchThreadsIndexRouteImport } from './routes/search/threads.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumsIndexRoute = ForumsIndexRouteImport.update({
  id: '/forums/',
  path: '/forums/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateThreadIndexRoute = CreateThreadIndexRouteImport.update({
  id: '/create-thread/',
  path: '/create-thread/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const UserIdIndexRoute = UserIdIndexRouteImport.update({
  id: '/user/$id/',
  path: '/user/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchThreadsIndexRoute = SearchThreadsIndexRouteImport.update({
  id: '/search/threads/',
  path: '/search/threads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/create-thread/': typeof CreateThreadIndexRoute
  '/forums/': typeof ForumsIndexRoute
  '/test/': typeof TestIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/search/threads/': typeof SearchThreadsIndexRoute
  '/user/$id/': typeof UserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/create-thread': typeof CreateThreadIndexRoute
  '/forums': typeof ForumsIndexRoute
  '/test': typeof TestIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/search/threads': typeof SearchThreadsIndexRoute
  '/user/$id': typeof UserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/create-thread/': typeof CreateThreadIndexRoute
  '/forums/': typeof ForumsIndexRoute
  '/test/': typeof TestIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/search/threads/': typeof SearchThreadsIndexRoute
  '/user/$id/': typeof UserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/create-thread/'
    | '/forums/'
    | '/test/'
    | '/api/auth/$'
    | '/search/threads/'
    | '/user/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/create-thread'
    | '/forums'
    | '/test'
    | '/api/auth/$'
    | '/search/threads'
    | '/user/$id'
  id:
    | '__root__'
    | '/'
    | '/demo/better-auth'
    | '/demo/tanstack-query'
    | '/create-thread/'
    | '/forums/'
    | '/test/'
    | '/api/auth/$'
    | '/search/threads/'
    | '/user/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  CreateThreadIndexRoute: typeof CreateThreadIndexRoute
  ForumsIndexRoute: typeof ForumsIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  SearchThreadsIndexRoute: typeof SearchThreadsIndexRoute
  UserIdIndexRoute: typeof UserIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forums/': {
      id: '/forums/'
      path: '/forums'
      fullPath: '/forums/'
      preLoaderRoute: typeof ForumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-thread/': {
      id: '/create-thread/'
      path: '/create-thread'
      fullPath: '/create-thread/'
      preLoaderRoute: typeof CreateThreadIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user/$id/': {
      id: '/user/$id/'
      path: '/user/$id'
      fullPath: '/user/$id/'
      preLoaderRoute: typeof UserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/threads/': {
      id: '/search/threads/'
      path: '/search/threads'
      fullPath: '/search/threads/'
      preLoaderRoute: typeof SearchThreadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  CreateThreadIndexRoute: CreateThreadIndexRoute,
  ForumsIndexRoute: ForumsIndexRoute,
  TestIndexRoute: TestIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  SearchThreadsIndexRoute: SearchThreadsIndexRoute,
  UserIdIndexRoute: UserIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
